services:
  app:
    image: 'node:20-alpine'
    entrypoint: /bin/sh
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - type: bind
        source: .
        target: /app
    tty: true
